  // contact list  
  var contactList = [
    {id: 0, name: 'Steve Rogers', email: 'cap@shield.com', phone: '905-615-3000', url: 'http://marvel.com/characters/8/captain_america', skills: 'Captain America has no superhuman powers, but through the Super-Soldier Serum and "Vita-Ray" treatment, he is transformed and his strength, endurance, agility, speed, reflexes, durability, and healing are at the zenith of natural human potential. His body regularly replenishes the super-soldier serum; it does not wear off.', notes: 'Although he lacks superhuman strength, Captain America is one of the few mortal beings who has been deemed worthy enough to wield Thor\'s hammer Mjolnir', image: 'captain_america.png' , wiki: "https://en.wikipedia.org/wiki/Captain_America"},
    {id: 1, name: 'Bruce Banner', email: 'hulk@shield.com', phone: '905-791-7800', url: 'http://marvel.com/characters/25/hulk', skills: 'The Hulk possesses the potential for seemingly limitless physical strength which is influenced by his emotional state, particularly his anger.', notes: 'Hulk.  The big green monster that smashes everything!', image: 'hulk.png' , wiki: "https://en.wikipedia.org/wiki/Hulk_(comics)"},
    {id: 2, name: 'Thor', email: 'thor@asgard.com', phone: '905-615-3206', url: 'http://marvel.com/characters/60/thor', skills: 'Like all Asgardians, Thor is incredibly long-lived and relies upon periodic consumption of the Golden Apples of Idunn to sustain his extended lifespan, which to date has lasted many millennia. Being the son of Odin and the elder goddess Gaea, Thor is physically the strongest of the Asgardians', notes: 'The crown Prince of Asgard', image: 'thor.png' , wiki: "https://en.wikipedia.org/wiki/Thor_(Marvel_Comics)"},
    {id: 3, name: 'Natasha Romanova', email: 'natasha@shield.com', phone: '418-852-9874', url: 'http://marvel.com/characters/6/black_widow', skills: 'Expert martial artist  The Black Widow is a world class athlete, gymnast, acrobat, aerialist capable of numerous complex maneuvers and feats. ', notes: 'The Black Widow', image: 'black_widow.png' , wiki: "https://en.wikipedia.org/wiki/Black_Widow_(Natasha_Romanova)"},
    {id: 4, name: 'Clint Barton', email: 'hawkeye@shield.com', phone: '845-985-9632', url: 'https://marvel.com/characters/23/hawkeye', skills: 'While Hawkeye has no superhuman powers, he is at the very peak of human conditioning. He is an exceptional fencer, acrobat and marksman, having been trained from childhood in the circus', notes: 'Hawkeye.  Master archer!', image: 'hawkeye.png' , wiki: "https://en.wikipedia.org/wiki/Hawkeye_(comics)"},
    {id: 5, name: 'Tony Stark', email: 'tony@stark.com', phone: '387-985-5421', url: 'http://marvel.com/characters/29/iron_man', skills:  'Iron Man possesses powered armor that gives him superhuman strength and durability, flight, and an array of weapons. The armor is invented and worn by Stark' , notes: 'A self-described genius, billionaire, playboy, and philanthropist with an electromechanical suit of armor of his own invention', image: 'iron_man.png' , wiki: "https://en.wikipedia.org/wiki/Iron_Man"},
    {id: 6, name: 'Maria Hill', email: 'maria@shield.com', phone: '251-351-25781', url: 'https://marvel.com/characters/2933/maria_hill', skills:  'Marksman and expert hand to hand combat practitioner.', notes: 'A high-ranking agent with S.H.I.E.L.D. who works closely with Nick Fury', image: 'maria_hill.png' , wiki: "https://en.wikipedia.org/wiki/Maria_Hill"},
    {id: 7, name: 'Nick Fury', email: 'nick@shield.com', phone: '784-254-3698', url: 'http://marvel.com/', skills:  'Fury is a seasoned unarmed and armed combat expert, was a heavyweight boxer in the army (during World War II), and holds a black belt in Tae Kwon Do and a brown belt in Jiu Jitsu', notes: 'The wily Colonel Nicholas Joseph Fury.  Tough as nails', image: 'nick_fury.png' , wiki: "https://en.wikipedia.org/wiki/Nick_Fury"}
  ];
